### ISSUE TITLE
Show visual representation of how popular a particular shard is within a category

### ISSUE THREAD

**Issue by edwardloveall** [jdbann/crystal-toolbox#2]
Here's what RubyToolbox looked like
![screen shot 2018-01-19 at 1 46 21 pm](https://user-images.githubusercontent.com/49549/35166247-336bea7a-fd1f-11e7-9ea9-5c3bb7475e34.png)

I don't think we necessarily need to do it that way, but that screenshot is the context for this feature.

In some ways, that feels like too much info. Do I really care that Vestal Versions and Acts as versioned are about 1/5 as popular as Papertrail? I just kind of want to know that Papertrail and Audited are the main pics (in that order) and then there's a bit of a mid tier, and a long tail. What do the numbers even mean? Why is there a Erlenmeyer flask icon next to the number?

**Comment by edwardloveall** [comment]
I was thinking about how we can even get this data. Rubygems is the centralized resource for gems, but there is no equivalent for shards. Github holds most shards but not all, and even then, there's not a "clone count" as far as I know in any API.

For an MVP, maybe we could do a search for some shard name in the shards.yml file of all project and count the number of results?

**Comment by jdbann** [comment]
I was going to go by stars and watchers as a rough initial metric for popularity.

I like the idea of going through dependencies in the `shard.yml` file but would that lead to a greater emphasis on shards used to build shards over shards used to build applications?

Clones would be available if we had shard owners grant access but that doesn't seem ideal either. https://developer.github.com/v3/repos/traffic/#clones

**Comment by edwardloveall** [comment]
Oh yeah, stars and watchers is a good idea. That's probably a pretty good representation of how popular they are. Great point also on dependancies getting a boost. Let's start with that and see how it shakes out, iterate from there.
